# diff_text.py
# Test if Levenshtein is applicable to automatically transcoded text
#
# 2025-09-22    PV

from Levenshtein import LevenshteinDistance

# "C:\Temp\Tanguy Pastureau\Tanguy Pastureau - France Inter 2017-2023 - Le billet de Tanguy Pastureau\Le billet de TanguyPastureau - 2017-12-12 - Georges Tron de retour dans l'actualité.txt"
# "C:\Temp\Tanguy Pastureau\Tanguy Pastureau - France Inter 2017-2023 - Le billet de Tanguy Pastureau\Le billet de TanguyPastureau - 2017-12-14 - Qui veut le 06 de Gérald Darmanin¿.txt"
s1 = "Tanguy Pastureau, ça va toujours ? – Ça va, oui, oui, oui, oui, absolument ! – On reparlent d'un homme qu'on avait oublié, Georges Tron. – Oui, Georges Tron, on l'avait zappé, comme avant lui les Rubik's Cube ou l'épilation en triangle. Tron, c'est un peu comme Michel Sapin, mais sans les bras, le seul qui, à cause de son, n'ose pas se rendre en Syrie. Mais en 2011, on ne parlait que de lui, deux collaboratrices l'accusant de viols et d'agressions sexuelles, alors qu'il était maire de travail dans les sonnes. Il y est toujours, depuis 95, il a moins changé de fonction que Michel Wallbeck de vieux depuis la trou. On l'avait alors traité de fétichies des pieds, ce sont ces gens qui ne sont pas attirés par Oscar Pistorius. Lui disait pas du tout, c'est de la réflexologie. Il massait les pieds des dames, seulement l'une d'elles se plaint d'attouchements vaginales, ce qui situait à priori loin des pieds, à moins d'être un tableau de Picasso, ou d'être passé sous un bus alors qu'on roulait en Vélib sur une voie partagée « Bus Vélib », l'une des plus grandes aberrations modernes avec la pizza à la nana. Dans le JDD, Tron réplique, il dit qu'il a juste fait des points de pression sur le pied qui explique-t-il qu'on prend 7200 terminés enerveuses, un pied c'est plus technologique qu'un iPhone X, et nous comme débuts, on laisse les champignons pousser dessus alors qu'on devrait les illustrer à la peau de chamois, en les appelant l'un mon chéri et l'autre mon amour. Et face aux accusations des plaignantes, George Tron est scié. Oui, car dit-il, il a massé les pieds de ses deux femmes, mais aussi ceux d'hommes allant jusqu'à 75 ans. En fait dès qu'elle qu'un entrait en mairie, lui disait « Toi, tu retires tes pompes, tes trésors que t'as dedans méritent mieux, on ne laisse pas ses pieds dans un coin ». Et il se mettait à les lui mal axés, comme quand on fait une patate arte mais en moins goûtue. Selon lui, ça restait amical, au méchouis du club des pétants qu'on sert la main des bolistes. Bon bah lui, il leur serrait les pieds, après il levé la jambe à la Johnny Clegg, il se mettait à crier « Eh, Franck, il tape moins 5 ». Puis il accuse les plaignantes, il dit de l'une d'elles qu'elle aurait détourné 5 000 euros en 20, des tournements de fonds dit de Benoît Poulverde, et de l'autre, il affirme que lors d'une soirée en mairie, elle aurait saisi les parties génitales de son adjoint, un mois qui me suis dirigé vers les médias pour qu'on me fasse ce genre de trucs. Au mieux, on m'a payé un kawa, en fait il ne se passe rien, on est tous claqués dès qu'on peut on d'or, donc il fallait juste que j'aille refaire ma carte d'identité à la mairie de Draveille dans les sonnes. Bref, Selon Trance et Collaboratrice cherchent à se venger, parce qu'il les a virés, et à l'abattre, à la hache ou à autre chose, le procès débute ce jour. Bah merci beaucoup Tanguy Pastureau."
s2 = "Vous avez des curieuses envies ce matin Tanguy Pastureau, vous avez une paire de Gérald Darmanin, pourquoi donc ? Oui, Gérald Darmanin c'est ce ministre qui a commis l'exploit d'être encore moins âgé que le président Macron. Plus jeune que lui, Macron était obligé de choisir un élève de 6e, un délégué de classe pour qu'il ait l'habitude du pouvoir. Darmanin est ministre des comptes publics, qui est à peu près aussi fun qu'une soirée passée avec Alain Finkelkraut quand on a envie d'un peu de calme. Le pauvre s'ennuie alors qu'il a encore l'âge de s'éclater en boîte avec Frédéric Bécbédé, qui lui n'a plus l'âge de s'éclater en boîte. Darmanin n'a que 35 ans et un physique de gamin, à tel point que parfois des types accolient de barbe l'arrête pour lui proposer des bonbons à la sortie du ministère. Et il le sait qu'il est un postado en pleine montée de sèvres coincés dans une existence de vieux, pile l'inverse de Jean-Luc Lais. Là il devrait écouter du Eminem en rêvant de partir à Goa pour les vacances, il devrait déjà être percé des deux tétons et avoir une vie de déglingosse. Mais il a celle de Baladur, le V6H, puis tri des dossiers, puis travail, puis Tizane, puis lui la brocante en DVD et au lit. C'est pourquoi Mardi soir, invité dans cet avoue, la seule émission où l'histoire se fout de feuilles de salade entre les dons et donc nous dégoûte. Il a donné en direct son 06. Ah ! Vous voulez dire que Gérald Darmanin, ministre, a dévoilé son numéro privé ? Oui, car il a très envie de pécho Gégé, il est autre que ma panignie 3 fromages, il l'a donné. Carpe Diem, il s'est dit rien Nafi, je suis un coupon. Et il a dit c'est le 06, 3315, 05, 85. Moi j'ai vu ça, j'ai eu l'impression de revenir en 87 que derrière 3615 Géraldine allait me proposer de faire des rencontres très chaudes dans ma région. Alors des journalistes ont tenté de l'appliquer, mais en vain, le répondeur était saturé. Tous les gens en manque de sexe ou simplement d'amour lui ont laissé un message vocal qui finissait par plus quelques crevards qui voulaient lui soutirer du brosouf. Il n'est aucun public, après rabotage par Macron, il gère quand même un pactole de 92,20 sur l'année. 06, 3315, 05, 85. Appelez Gérald, tout le monde n'a Dieu que pour Emmanuel et lui, alors on laisse pas Gégé dans un coin. 06, 3315, 05, 85. Épargnez-lui un appel à SOS Amitié. Tu es un peu cochon, tu aimes le centre. Appelle le 06, 3315, 05, 85. Toi aussi tu es ministre et tu sais qu'il faut pas lâcher ton fontel comme si t'étais Zaya en face de Prospection. Dis-le à Gérald, 06, 3315, 05, 85. Surtout pas de messages méchants, il a besoin d'amour. 06, 3315, 05, 85. On devrait tous faire ça et s'aimer les uns les autres. Laetitia, Léa, Salamé. Allez-y, lâchez votre 06, on s'en fout. Star de la radio ou pas, c'est comme dans le vestiaire de foot. On est tous pareil. 06, 3315, 05, 85. On vous aime, Monsieur Darmanin."
print("len(s1)=", len(s1))
print("len(s2)=", len(s2))

d = LevenshteinDistance(s1, s2, 999999)
print("d=", d)
