bib = []
bib.append(("Bibliothèque Tangente HS 18, Les fractales, Art, nature et modélisation - 2è ed, 2019",
"""Le terme « fractal » fait immédiatement surgir de saisissantes images, colorées, infiniment complexes, fascinantes. Elles ne peuvent donc que séduire, au point d'inspirer de nombreux artistes, ce qui conduit aux images de toute beauté de cet ouvrage très visuel.
Ces magnifiques objets géométriques possèdent une définition mathématique qui reste à la portée de tous. Le principe: les formes fractales restent identiques à elles-mêmes, quelle que soit l'échelle à laquelle on les regarde. On les retrouve dans la nature, de la forme des côtes bretonnes déchiquetées à celle des nuages, en passant par les fougères ou les choux Romanesco. Benoît Mandelbrot, le « père des fractales », a œuvré toute sa vie pour que change notre regard sur les formes qui nous entourent.
La structure fractale se rencontre dans de nombreux domaines: biologie, médecine, compression d'images, théorie du signal, finance, acoustique, cinéma..."""))
bib.append(("Bibliothèque Tangente HS 23, Mathématiques et arts plastiques, La géométrie de la création - 2è ed, 2019",
"""Les clés de toute oeuvre mathématique sont la créativité, l'originalité, la beauté, le caractère d'évidence, l'achèvement. C'est aussi ce qui caractérise une oeuvre d'art. Dès lors, un dialogue fécond entre arts et mathématiques s'établit naturellement, d'autant que les techniques mathématiques peuvent se mettre au service de l'art.
Les notions de perspective, de symétrie, de trompe-l’œil, d'anamorphose ou de fractale relèvent aussi bien de la peinture que de la science. L'architecture et les décors de l’Alhambra de Grenade fascinent encore aujourd'hui, tout comme les peintures abstraites de Piet Mondrian, Paul Klee, François Morellet, Vassily Kandinsky ou Victor Vasarely. Aussi loin que l'on remonte dans le temps, mathématiques et arts sont entremêlés.
Voyage complet et documenté, visuellement plaisant, à travers ces liens, évidents ou insoupçonnés, que les artistes et les mathématiciens tissent depuis des siècles."""))
bib.append(("Bibliothèque Tangente HS 32, Mathématiques et finance, Crédits, bourse, marchés à terme - 2è ed, 2019",
"""Le vocabulaire de la finance met en avant des mots familiers comme « taux », « indices », « variations », « inflation », souvent empruntés à l'analyse mathématique. Ce n'est pas un leurre. Le prix d'une option - droit d'acheter ou vendre un actif - est fixé à partir de l'équation dite « de Black et Scholes », ce dernier ayant obtenu le prix Nobel d'économie en 1997, et toute étude sérieuse des cours de la bourse requiert une analyse statistique poussée.
Cet ouvrage, à la fois accessible et technique, s'adresse à tous ceux qui rêvent d'avoir les clés des rouages du monde de la banque et de la finance sans avoir à suivre une formation spécialisée: du néophyte qui s'interroge sur le taux d'intérêt de son crédit, au professionnel de la bourse qui découvrira les modèles sous-jacents et l'apport de l'IA.
Cette nouvelle édition aborde l'analyse de la gestion d'une crise et fournit des réponses objectives au débat sur la validité des modèles mathématiques et leur responsabilité souvent (à tort) mise en avant. Elle précise également le rôle et le fonctionnement des autorités de régulation."""))
bib.append(("Bibliothèque Tangente HS 33, Les nombres, Secrets d'hier et d'aujourd'hui - 2è ed, 2019",
"""On utilise tous les jours les nombres, objets mathématiques de base, dans de nombreux contextes. Mais de quoi parle-t-on? Des entiers positifs, servant à compter, à l'origine d'une formidable histoire qui commence avec leur construction, marquée par l'apparition du zéro et l'avènement des systèmes de numération pour les représenter? Des nombres négatifs, qui mesurent essentiellement les variations? Des nombres imaginaires, qui ont tellement mis de temps à s'imposer, indispensables outils de l'ingénieur? Des nombres algébriques, racines des équations à coefficients entiers? Et il y en a bien d'autres!
Vous vibrerez avec certains des visionnaires, professionnels ou amateurs, qui par milliers ont brûlé des jours et des nuits pour découvrir d'insoupçonnées propriétés.
Mais l'ouvrage vous livrera aussi de vrais secrets: depuis certaines curiosités amusantes jusqu'aux applications les plus confidentielles de ce qu'on appelle aujourd'hui la théorie des nombres."""))
bib.append(("Bibliothèque Tangente HS 38, Mathématiques et philosophie, En quête de vérités - 2è ed, 2019",
"""Philosophie et mathématiques sont nées simultanément du regard que les humains portent sur le monde qui nous entoure. Il est possible d'aborder les grands sujets philosophiques liés aux mathématiques, sans concessions ni censure, en restant à la portée de tous. Les grandes notions, voire les grandes querelles, sont toutes présentes, ou presque: l'infini, la logique, le hasard, le débat sur la vision platonicienne des mathématiques, l'existence de Dieu, la révolution des théorèmes de Gödel, les paradoxes, l'esthétique, l'intuition...
Merci à tous ceux - mathématiciens, philosophes, ou les deux à la fois - que cet ouvrage à réunis: Aristote, Platon, Pascal, Descartes, Leibniz, Poincaré, Wittgenstein, et bien d'autres! Les enjeux de leurs questionnements, de leurs échanges, de leurs controverses, sont exposés ici, pour le plus grand bonheur de nos lecteurs, qui y trouveront une source inépuisable de matière pour réfléchir sur le monde."""))
bib.append(("Bibliothèque Tangente HS 39, Mathématiques discrètes & combinatoire, L'art de dénombrer - 2010",
"""Compter, dénombrer. S'il paraît simple de compter, il n'est pas facile de maîtriser l'art du dénombrement. Parmi les outils disponibles, la combinatoire est la discipline privilégiée. Elle est à l'origine de la théorie des probabilités. Mais les mathématiques discrètes, qui consistent à étudier tous les problèmes que l'on pourrait résoudre en franchissant un certain nombre (fini) d'étapes, ne se limitent pas au dénombrement. Elles se sont enrichies de nombreux développements plus récents: les graphes, les arbres, les réseaux, une zoologie de nombres, et bien d'autres objets. Les maths discrètes sont incontournables en informatique, en théorie des jeux, dans les problèmes de décision, et dans la plupart des sciences."""))
bib.append(("Bibliothèque Tangente HS 41, Suites & séries, Les nombres avec ou sans limite - 2011",
"""La recherche de la loi qui préside à la constitution d'une suite et donne lieu aux fameux tests de logique n'est qu'un minuscule aspect de la richesse que revêt l'étude des suites.
Suites de nombres, suites de fonctions, convergence, divergence, limite... Le sujet est vaste et occupe depuis des siècles de nombreux savants, de Riemann à Cauchy. Les amateurs ne sont d'ailleurs pas en reste: on leur doit une multitude de suites, qui figurent aujourd'hui sur le site de référence de Neil Sloane.
Mais les suites numériques conduisent, à partir du souci naturel de vouloir les sommer, à une théorie d'une grande richesse: celle des séries."""))
bib.append(("Bibliothèque Tangente HS 43, Maths & chimie, Des liaisons insoupçonnées - 2012",
"""Les mathématiques et la chimie sont deux piliers de la science moderne. Leurs origines sont séculaires et leurs racines profondes: les Grecs anciens associaient déjà la matière à certains polyèdres. Par la suite, un géant tel que Newton se passionnait pour l'alchimie aussi bien que pour les lois mathématiques qui régissent le monde physique. Quant au XXè siècle, il marque l'avènement de la conception quantique du monde. Aujourd'hui, de la cristallographie au génie chimique en passant par les oxydoréductions, la thermochimie ou l'atomistique, il apparaît que les mathématiques discrètes, les transformations géométriques, les fractales, les systèmes dynamiques ou les équations aux dérivées partielles sont indispensables. Venez découvrir que, là encore, le cloisonnement n'est pas de mise!"""))
bib.append(("Bibliothèque Tangente HS 45, Maths & politique, Dans la sphère du pouvoir - 2012",
"""« Gouverner, c'est prévoir » selon Émile de Girardin. L'art de la prévision étant régi par les mathématiques, on peut s'attendre à ce que les hommes d'État accordent un grand crédit à cette discipline.
Déjà dans l' Antiquité, philosophes et mathématiciens étaient très étroitement mêlés à la vie et au bon fonctionnement de la Cité. Ces relations sont encore plus fortes aujourd'hui que la politique s'occupe d'économie, de social, de démographie et de questions sociétales. Elles ont inspiré plusieurs thèmes de cet ouvrage:
- Principe de précaution
- Modèles des retraites
- Calcul de l'impôt
- Manipulation des chiffres...
Les outils utilisés sont ceux de la statistique, de la théorie des jeux, de l'aide à la décision et des mathématiques sociales, autant d'instruments qui sont indispensables à une gouvernance saine et rationnelle."""))
bib.append(("Bibliothèque Tangente HS 48, Ambassadeurs français des mathématiques - 2013",
"""Ils ont fait connaître et aimer les mathématiques, ils ont donné envie d'en savoir plus, ils ont suscité des vocations, ils ont porté haut les couleurs de la France.
• Scientifiques, philosophes, chercheurs, ils ont inventé des concepts tellement puissants que leurs noms sont connus et admirés dans le monde entier.
• Animateurs, magiciens, créateurs de jeux, ils ont su soulever les foules autour des événements qu'ils ont créés, de l'intérêt ou l'étonnement qu'ils ont suscité. Enseignants, ils ont présenté les mathématiques autrement, mis en avant leur composante culturelle.
• Écrivains, chroniqueurs, journalistes, ils ont eu le talent d'intéresser un vaste public en diffusant, vulgarisant, popularisant la culture mathématique.
C'est à ces ambassadeurs des mathématiques, célèbres et anonymes, qui ont consacré leur énergie à promouvoir une autre image des mathématiques, que cet ouvrage est consacré."""))
bib.append(("Bibliothèque Tangente HS 51, Mathématiques, de l'esthétique à l'éthique, Une dimension insoupçonnée - 2014",
"""Les mathématiques constituent un trait d'union privilégié entre le beau et le bon. La peinture, la sculpture ou la littérature y trouvent souvent leur source d'inspiration.
Mais ce n'est pas la seule relation entre mathématiques et esthétique. Tous ceux qui les pratiquent vous le diront, les maths elles-mêmes sont belles! Les structures cachées d'un problème, les analogies entre deux domaines a priori indépendants, le plaisir de chercher (et parfois de trouver) en attestent.
Si elles semblent n'exister que par notre cerveau et n'avoir aucun correspondant dans le monde sensible, les mathématiques possèdent d'innombrables applications concrètes, à travers les modèles qui reposent sur elles. Certaines d'entre elles, utilisées dans des contextes sensibles (guerre, finance, évaluation), doivent être questionnées. C'est une question d'éthique scientifique."""))
bib.append(("Bibliothèque Tangente HS 55, Les démonstrations, Raisonner et prouver - 2015",
"""La possibilité de convaincre avec une absolue certitude fait à elle seule la spécificité des mathématiques. Mais les bases de la logique sont-elles immuables? Qu'est-ce qu'une preuve? Peut-on convaincre avec un dessin ou un programme informatique? Une affirmation est-elle nécessairement vraie ou fausse?
De la méthode d'exhaustion d'Archimède au raisonnement par récurrence, la variété des méthodes utilisées pour démontrer est impressionnante. Mais tout l'art consiste à comprendre quelle technique de raisonnement s'applique à un problème donné, et à faire preuve de créativité quand la seule façon de convaincre consiste à sortir des sentiers battus.
Des sentiers où l'on rencontre pêlemêle paradoxes, contre-exemples, idées géniales, preuves sans mots, et esthétique..."""))
bib.append(("Bibliothèque Tangente HS 56, Les fonctions, Des nombres en correspondance - 2016",
"""La notion de fonction se précise tardivement, au XVIIè siècle, pour les besoins de la physique. Il devient possible, grâce au calcul infinitésimal, d'étudier les trajectoires, vitesses et accélérations d'objets en déplacement, comme une bille... ou une planète. L'intuition physique doit alors faire place à la rigueur d'un raisonnement mathématique. Sur quels objets les calculs peuvent-ils porter? Sur des fonctions, précisément!
Le succès est immédiat et foudroyant: l'analyse mathématique se révèle un outil incomparablement efficace pour expliquer et prédire tous les phénomènes physiques connus. Depuis, les notions de continuité, dérivabilité, quantités variables, ont essaimé dans toutes les sciences, et bien au-delà.
Aujourd'hui, les fonctions sont cachées dans nos ordinateurs, smartphones et autres tablettes: un programme est une fonction. Une « appli » est une fonction. Le GPS utilise des fonctions, pour vous localiser comme pour calculer votre itinéraire. De même, tout calcul économique ou financier découle de l'application d'une fonction bien choisie. Tout semble pouvoir se mettre en équation!"""))
bib.append(("Bibliothèque Tangente HS 57, Les mathématiques des assurances, Tous concernés assurément! - 2016",
"""Savez-vous que les premières rentes viagères datent de l'Antiquité? À cette époque, évidemment, les calculs ne reposaient pas sur des modèles bien élaborés: ce n'est qu'au XVIIIè siècle que la statistique a émergé en tant que discipline scientifique autonome.
Pour cela, il a fallu surmonter de nombreux défis: collecter de manière fiable des informations pour établir des tables de mortalité, traiter de grandes quantités d'informations, sans parler de la conception de nouveaux modèles de plus en plus sophistiqués qu'il faut reconstruire en permanence.
Aujourd'hui, on peut mettre ses proches à l'abri, protéger ses avoirs et même ses animaux, se prémunir contre des risques financiers ou même climatologiques, assurer ses vieux jours. Tout cela a été rendu possible grâce à l'émergence des mathématiques du hasard. Les actuaires manipulent des chaînes de Markov ou des processus stochastiques. Ils créent des systèmes décisionnels complexes pour nous proposer des couvertures adaptées à nos besoins de certitude, dans un monde fondamentalement incertain."""))
bib.append(("Bibliothèque Tangente HS 58, Mathématiques et médecine, Les maths au service de notre santé - 2016",
"""L'usage des probabilités et des statistiques pour dépister des pathologies ou pour tester vaccins et médicaments, la modélisation pour comprendre et contrecarrer la propagation d'une épidémie, sont des applications désormais classiques des mathématiques à la médecine. Que d'avancées depuis Pythagore et Hippocrate!
Mais aujourd'hui, en particulier grâce à l'apport des nouvelles technologies, les mathématiques sont plus que jamais mobilisées: pour lutter contre le cancer, pour concevoir des instruments d'imagerie, pour interpréter des données médicales... Les progrès couplés de l'informatique, de la biologie, de la chimie et de toutes les branches des mathématiques (équations aux dérivées partielles, analyse numérique, aide à la décision, systèmes dynamiques, théorie du signal...) autorisent tous les espoirs."""))
bib.append(("Bibliothèque Tangente HS 61, Les ensembles, Aux fondements des mathématiques - 2017",
"""La théorie des ensembles a laissé un souvenir à tous ceux qui sont passés par les « maths modernes ». Son cadre axiomatique, que certains ont pu percevoir comme rigide, permet de « dérouler » l'ensemble du savoir mathématique. Comment? C'est ce que propose de découvrir cet ouvrage en levant le voile sur l'origine et la construction de cette théorie.
Tout est parti d'un malaise scientifique profond, la crise des fondements. L'édifice mathématique, que l'on croyait solide et inaltérable, était en fait morcelé de contradictions et d'objets mal définis! L'introduction des ensembles à la fin du XIXe siècle a permis d'assainir la situation, tout en donnant naissance à son lot de paradoxes, d'impossibilités, de situations défiant l'intuition...
Un ensemble est une collection d'objets entre lesquels peuvent exister des relations diverses. C'est ainsi qu'émergent les notions de structures et de fonctions, qui régissent la majorité des concepts mathématiques. La construction des nombres et une nouvelle approche de la géométrie en découlent de manière naturelle. Une telle simplicité conceptuelle confère aux ensembles et aux fonctions une efficacité redoutable!
Mais choisir les bons axiomes pour développer la théorie des ensembles et décrire les mathématiques (et, au-delà, toutes les sciences!) n'est pas une mince affaire..."""))
bib.append(("Bibliothèque Tangente HS 62, Mathématiques et économie, Une vision scientifique de l'économie - 2018",
"""L'économie n'a pas toujours fréquenté les mathématiques, jusqu'à l'arrivée de penseurs qui, au XIXè siècle, y ont fait entrer la rationalité scientifique. L'économie peut dès lors être considérée comme une science.
Quel rôle les modèles mathématiques jouent-ils dans son analyse et son développement? Peuvent-ils contrebalancer les décisions reposant sur une approche dogmatique, et donc influencer le politique?
C'est ce que développe cet ouvrage, en s'intéressant successivement aux deux principaux versants de l'économie:
- La macroéconomie, qui étudie la production et l'échange de biens de consommation, avec ses notions essentielles comme la monnaie, l'inflation, le PIB ou les indicateurs
- La microéconomie, qui concerne les interactions marchandes à l'échelle des individus
Derrière leur modélisation, les principaux domaines des mathématiques interfèrent quotidiennement avec les systèmes de décision et de gestion. Parmi eux, les statistiques, les probabilités et les outils de l'analyse stochastique sont de plus en plus sollicités."""))
bib.append(("Bibliothèque Tangente HS 63, Les nombres complexes, Quand algèbre, analyse et géométrie se rejoignent - 2018",
"""Des nombres dont le carré est négatif! Les imaginaires, purs ou non, ont mis des siècles à être acceptés.
Ils ont donné naissance aux nombres complexes, créés à l'origine pour résoudre des équations algébriques. Cette découverte a bouleversé les mathématiques. Algèbre, analyse, géométrie, trigonométrie, disposaient désormais d'un outil puissant qui allait déboucher sur des découvertes fondamentales et permettre de nouvelles formes de démonstrations.
Au-delà des mathématiques, les complexes ont des applications dans de nombreux domaines, scientifiques, bien sûr, mais aussi plus inattendus.
La technologie et même l'art leur doivent beaucoup. Du lycéen au scientifique professionnel, du technicien à l'artiste, personne ne peut se passer des nombres complexes."""))
bib.append(("Bibliothèque Tangente HS 64, Découpages et pavages, Entre art et géométrie - 2018",
"""Deux figures de même aire peuvent-elles toujours être obtenues, l'une à partir de l'autre, à l'aide d'une simple paire de ciseaux? Un théorème fameux répond à la question...
Les découpages et pavages, qui se retrouvent dans toutes les civilisations sous forme de récréations, s'avèrent une composante essentielle de la géométrie, permettant en particulier des démonstrations visuelles simples et élégantes. Les carrés, les rectangles, les polygones et polyminos fournissent une mine inépuisable d'énigmes et de puzzles.
Roger Penrose et Maurits Escher ont été les précurseurs de nouvelles mosaïques étonnantes et magnifiques dont les artistes musulmans avaient déjà entrevu les richesses et qui ont débouché sur les pavages réguliers et les frises, aujourd'hui catalogués de manière rigoureuse. Tout devient encore plus étonnant quand on généralise les concepts, tant des découpages que des pavages, à l'espace ou à la surface d'une sphère."""))
bib.append(("Bibliothèque Tangente HS 65, Vecteurs et espaces vectoriels, Une nouvelle approche de la géométrie - 2018",
"""Le concept de vecteur, puis d'espace vectoriel, s'affine progressivement tout au long du XIXè siècle dans le but de formaliser l'espace qui nous entoure. Des éléments fondamentaux sont introduits: base, dimension, déterminant, application linéaire...
La géométrie, et c'est une révolution, peut être traitée comme une branche de l'algèbre. Cette nouvelle approche apporte des solutions miraculeuses à certains problèmes réputés difficiles. L'espace vectoriel a ensuite conquis peu à peu les grands continents mathématiques que sont l'algèbre et l'analyse, puis l'ensemble des sciences.
Qui, mieux qu'un vecteur, peut encoder la direction, le sens, la force d'un mouvement? Que ce soit pour retoucher une image numérique, évaluer l'orbite d'un corps céleste ou réaliser le calcul approché d'une intégrale, on ne peut plus s'en passer!
De nombreuses applications sont mises en évidence, dans des domaines variés: le dessin vectoriel, le traitement de données de masse, et même des techniques de composition musicale, illustrées par Iannis Xenakis."""))
bib.append(("Bibliothèque Tangente HS 66, Les secrets des dimensions, Plan, espace, 4D, Passeport pour un nouvel univers - 2019",
"""L'intuition visuelle qui règne dans la géométrie plane est souvent prise en défaut lorsque l'on passe à la 3D. Alors que cercles, triangles et autres polygones ne posent pas de difficultés, (se) représenter les volumes n'est pas si évident.
Le thème de la dimension est omniprésent en mathématiques. Il offre l'occasion de revisiter les liens entre 2D et 3D en se penchant sur les techniques de représentation imaginées depuis la Renaissance par architectes, astronomes ou artistes: utilisation de patrons, systèmes de projections (stéréographiques, géométrie descriptive), et, bien sûr, perspective.
Ces dialogues entre le plan et l'espace ne sont pas seulement géométriques: ils sont également topologiques, et ont ensuite, de façon naturelle, débouché sur la quatrième dimension... et plus encore! D'autres branches des mathématiques sont alors conviées pour révéler les secrets des dimensions.
Ce sont toutes ces explorations que propose ce livre très visuel de la Bibliothèque Tangente."""))
bib.append(("Bibliothèque Tangente HS 67, Mathématiques du développement durable, Une équation délicate - 2019",
"""Le développement durable est un thème d'actualité autour duquel circulent de nombreuses informations. Parmi elles, il faut savoir distinguer les faits avérés, essentiellement liés à des observations passées, les projections vers l'avenir, qui s'appuient sur des modèles mathématiques, mais ne convergent pas toujours, et les affirmations erronées qui sont une constante quand un dogme est en jeu.
Cet ouvrage s'efforce de dresser un panorama objectif des outils mathématiques utilisés dans la modélisation du climat, dans l'analyse des sources d'énergie ou dans les prévisions d'évolution des populations.
Il étudie les solutions proposées, qui ne sont pas si simples, voire parfois même déroutantes.
En effet, de multiples paradoxes émergent lorsque l'on creuse certains sujets, comme celui des transports. Car toutes les questions posées par le développement durable sont interconnectées et une solution à l'un des problèmes peut avoir des répercussions pas forcément très heureuses sur d'autres domaines."""))
bib.append(("Bibliothèque Tangente HS 68, Intelligence artificielle, L'alliance des mathématiques et de la technologie - 2019",
"""L'essor foudroyant de l'intelligence artificielle est d'une ampleur sans précédent, de nature à transformer des pans entiers de notre monde: une révolution se prépare, tant du côté des applications que du côté théorique. Des voitures autonomes à la traduction automatique, des stratégies de jeux de société à la gestion de ressources, l'IA s'immisce partout dans nos vies. Les mathématiques contribuent de manière significative à cette révolution, avec notamment les réseaux de neurones artificiels, massivement utilisés dans de nombreuses applications.
Cet ouvrage, auquel ont collaboré des spécialistes reconnus, donne les clés permettant de comprendre cette évolution fondamentale dans la façon même d'envisager le travail de l'ordinateur. Il en précise les enjeux intellectuels, industriels, mais aussi éthiques."""))
bib.append(("Bibliothèque Tangente HS 69, Mathématiques et physique, Destins croisés - 2019",
"""Dans l'histoire du développement de la pensée scientifique, les mathématiques ont été sollicitées depuis l'Antiquité pour résoudre des problèmes concrets liés à la physique et aux interrogations autour de l'astronomie. À l'inverse, cette interaction a engendré d'importants progrès dans le développement des mathématiques.
Quelques siècles plus tard, sous l'impulsion de Joseph Fourier, est née la physique mathématique, qui place les équations au coeur de la démarche du physicien. Les puissantes théories qui voient alors le jour n'ont pas encore livré tous leurs secrets.
Le rapport entre les deux disciplines évolue de manière forte. Après la méthode synthétique de Newton, la méthode analytique de Lagrange exploite la puissance du calcul intégral et donne naissance à la théorie des équations différentielles. Le partenariat maths-physique continue d'évoluer et s'ouvre sur un nouveau regard, plus largement développé dans un autre volume de cette collection (le n°71, juin 2020) consacré aux théories modernes (relativité, physique quantique)."""))
bib.append(("Bibliothèque Tangente HS 70, Les surfaces, Le rendez-vous des géométries - 2020",
"""Comment définir précisément une surface? La première approche, adoptée dès l'Antiquité, est celle de la géométrie. Sont ensuite venues l'algèbre, l'analyse et la topologie.
Chacune de ces branches a permis d’enrichir le catalogue des surfaces remarquables et d'en imaginer d' autres, plus élégantes ou plus... pathologiques. Le ruban de Mobius, qui ne possède qu'un seul « côté », défie notre intuition, tout comme certaines opérations « choquantes », comme celle qui permet, dans le cadre des fractales « lisses », de déformer une sphère de la taille de la Terre en une balle de ping pong... sans modifier les distances entre les points de la surface!
Les surfaces ont également fait rêver de nombreux architectes, de Gustave Eiffel à Vladimir Choukhov. Quant aux artistes, concepteurs ou plasticiens, ils ont détourné les surfaces selon leur inspiration, du tricot à l'infographie, des bulles de savon à l'assemblage mécanique."""))
bib.append(("Bibliothèque Tangente HS 71, Les équations de la physique moderne, Relativité générale, Mécanique quantique - 2020",
"""Les grandes théories physiques ont été imaginées abstraitement avant d'être (ou non) validées, parfois longtemps après, par des observations. Des scientifiques audacieux ont su adosser, au début du XXè siècle, une partie de la physique à des concepts mathématiques.
L'arrivée des théories relativistes imaginées par Albert Einstein a bouleversé notre compréhension de l'univers, détrônant l'approche newtonienne. Les équations du nouveau modèle réservent leur lot de surprises mathématiques. La gravitation devient une manifestation de la géométrie, les espaces non euclidiens s'imposent, les tenseurs ouvrent de nouveaux formalismes, les distributions permettent de généraliser le concept de fonction. Les physiciens disposaient ainsi d'une grande théorie universelle qui allait leur permettre d'explorer méthodiquement l'univers.
L'infiniment grand, peut-être! Mais le monde subatomique refusait encore de se soumettre. Les mathématiques ont été convoquées afin de formaliser les phénomènes contre-intuitifs qui ont cours en physique quantique."""))
bib.append(("Bibliothèque Tangente HS 72, Maximum Minimum Optimum, L'art de faire au mieux - 2020",
"""La construction progressive de l'analyse, en particulier la dérivation, a joué un rôle essentiel dans le développement de la théorie des extrema. Mais, parallèlement au calculus, d'autres voies se sont ouvertes pour offrir de nouveaux paradigmes et étendre le champ des résultats théoriques et celui des applications.
Dans un contexte plus géométrique, par un processus de type essai/erreur, la nature a progressivement développé des solutions optimales. Mais des mathématiciens s'y sont également employés, utilisant entre autres les outils du calcul différentiel, au point que ces derniers ont parfois fini par rendre presque méconnaissables les aspects géométriques des problèmes traités. Les techniques de la combinatoire sont également sollicitées. La recherche de solutions explicites passe souvent par la construction d'algorithmes. Lorsque ce n'est pas possible, le recours à des méthodes heuristiques approchant les résultats est parfois nécessaire.
Les applications des méthodes d'optimisation sont nombreuses, de la notion de plus court chemin à des domaines comme l'économie ou même la psychologie."""))
bib.append(("Bibliothèque Tangente HS 73, Maths et emploi, Un monde professionnel très demandeur - 2021",
"""Les formations mathématiques font partie des plus demandées par le monde professionnel. On le savait pour la finance, l'économie ou l'informatique, mais la compétence mathématique est au coeur de la demande de nombreux autres secteurs industriels. De nouveaux concepts théoriques se créent pour répondre à ces besoins, mobilisés par des domaines variés, comme l'aéronautique, la 5G ou le traitement d'image où les mathématiques permettent de gérer la compression, la transmission, le débruitage et la restauration de fichiers numériques.
On assiste ainsi au développement de la géométrie de l'information, née de la volonté de géométriser les espaces de distributions de probabilité, ou du calcul à haute performance, reposant sur l'utilisation de multiples unités de calculs très intensifs.
Plus généralement, les entreprises, plongées dans un environnement qui évolue régulièrement, sollicitent de plus en plus les mathématiques et recrutent des ingénieurs comme des diplômés de l'université."""))
bib.append(("Bibliothèque Tangente HS 74, Courbes et trajectoires, Entre algèbre et géométrie - 2021",
"""De leur histoire ancienne, remontant à plusieurs millénaires, aux découvertes plus récentes, les courbes ont fait l'objet de recherches permanentes.
Entre algèbre et géométrie, leur définition n'est d'ailleurs pas toujours simple! Droites, cercles, coniques, spirales... Les plus connues sont, naturellement, les courbes planes, dont les propriétés et les modes de construction ont passionné de nombreux mathématiciens.
La physique et l'astronomie ont ensuite débouché sur une extrapolation en dimension 3, car une courbe, c'est aussi la trajectoire d'un point, dans le plan comme dans l'espace.
Aujourd'hui, elles sont omniprésentes dans notre quotidien, utilisées par les statistiques, les circuits routiers, l'architecture, la conception graphique et l'art."""))
bib.append(("Bibliothèque Tangente HS 75, La recherche opérationnelle, Des mathématiques pour décider et organiser - 2021",
"""Apparue lors de la seconde guerre mondiale dans un contexte militaire qui lui a donné son nom, la recherche opérationnelle, à la croisée des mathématiques, de l'informatique et de l'économie, s'est étendue à tous les domaines de la société. Entreprises, collectivités territoriales, administrations, établissements scolaires, hôpitaux et même individus doivent chaque jour résoudre des problèmes d'organisation.
Les outils de modélisation mathématique permettent de décrire un contexte avant de mettre en oeuvre des méthodes de résolution dédiées. Ainsi, la théorie des graphes aidera à mieux organiser des tournées, et donc réaliser des économies substantielles de temps et de carburant. L'algorithmique servira à améliorer une chaîne de production. L'optimisation s'invitera pour la fabrication ou la commande de fournitures. Les mathématiques de la décision seront, quant à elles, utiles lors d'un choix collectif."""))
