- podcast: Tanguy Pastureau maltraite l'info
  url: https://radiofrance-podcast.net/podcast09/rss_18141.xml
  path: D:\Temp\Podcasts\Tanguy Pastureau
  last_download:

- podcast: Charline explose les faits
  url: https://radiofrance-podcast.net/podcast09/rss_13129.xml
  path: D:\Temp\Podcasts\Charline Vanhoenacker
  last_download:
