podcasts:
- podcast: Tanguy Pastureau maltraite l'info
  url: https://radiofrance-podcast.net/podcast09/rss_18141.xml
  path: D:\Podcasts\Tanguy Pastureau
  last_download: '2025-10-20T10:15:00+00:00'
- podcast: Charline explose les faits
  url: https://radiofrance-podcast.net/podcast09/rss_13129.xml
  path: D:\Podcasts\Charline Vanhoenacker
  last_download: '2025-10-20T07:49:50+00:00'
- podcast: La chronique de Yann Marguet
  url: https://radiofrance-podcast.net/podcast09/rss_23943.xml
  path: D:\Podcasts\Yann Marguet
  last_download: '2025-10-16T15:57:00+00:00'
- podcast: La question de David Castello-Lopes
  url: https://radiofrance-podcast.net/podcast09/rss_24413.xml
  path: D:\Podcasts\David Castello-Lopes
  last_download: '2025-10-16T06:58:30+00:00'
- podcast: Le billet de Bertrand Chameroy
  url: https://radiofrance-podcast.net/podcast09/rss_25633.xml
  path: D:\Podcasts\Bertrand Chameroy
  last_download: '2025-10-16T05:59:15+00:00'
- podcast: Le Billet de Daniel Morin
  url: https://radiofrance-podcast.net/podcast09/rss_12371.xml
  path: D:\Podcasts\Daniel Morin
  last_download: '2025-10-20T05:59:15+00:00'
- podcast: Lisa Delmoitiez n'aurait pas fait comme ça
  url: https://radiofrance-podcast.net/podcast09/rss_23711.xml
  path: D:\Podcasts\Lisa Delmoitiez
  last_download: '2025-10-17T09:20:00+00:00'
