import os
from common_fs import file_exists

files = [
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2014-01-14 - «Moi président...«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2014-02-18 - «Made in France ¿ « .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2014-10-27 - Fleur Pellerin atteinte de «phobie littéraire«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2015-09-01 - Benoît Poolvoerde, ce «Moïse« qui a ouvert la mer du show-biz français.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2015-09-15 - Les «bolchos« n'ont pas d'humour ¿ .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2015-11-17 - «Nous sommes belges, et on ne voudrait pas qu'il y ait d'amalgame«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2016-01-12 - Jean-Pierre Raffarin ,«to win against the right«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2016-04-26 - «Idéologiquement, je suis profondément européen«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2016-08-23 - Pokémon go, et non pas «Anne Hidalg Go« .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2017-02-21 - «Au temps béni des colonies...«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2017-09-05 - Christophe Castaner, une sorte de «sous Bruno Roger-Petit«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2017-11-21 - «Vermine cosmopolite«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2017-12-19 - «Punir pour prévenir«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2019-01-08 - «Laissons les jeunes femmes aux hommes sans ambition«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2019-03-12 - Le «parenting«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2019-12-27 - Les citations et les «inspirateurs«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2020-04-21 - Théâtre , «En attendant le public«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2020-06-02 - Le racisme avec Céline Dion , «Tout aurait été plus simple, si on était descendu du caméléon«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2020-09-15 - «Hommes impuissants«, le livre d'Alex Vizorek.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2020-12-24 - «La« Covid.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2020-12-30 - Octobre 2020 , des décisions fortes sont prises, «StopCovid« devient «TousAntiCovid«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2021-12-22 - Mars 2021 , «Dedans avec les miens, dehors en citoyens !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2022-03-15 - A quand «Marioupol au premier regard« ou «Top Kiev« ¿.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2022-03-22 - La nouvelle chaîne radio «France Travail«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2023-02-07 - «Je m’en bats la queue au plafond jusqu’à production d’étincelles«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Alex Vizorek\2023-05-02 - «Le Masque et la Plume« , qui après Jérôme Garcin ¿.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2014-02-13 - «Copé décalé«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2014-04-22 - «Le Grand bleu« avec une chaussure noire.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2014-05-19 - Ceci n'est pas un «tweet«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2014-09-01 - La «révolution raisonnable«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2014-10-07 - «Le doudou de Sarkozy«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-01-14 - «Charlie Madame«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-01-22 - Le pape a dit , «Ne soyez pas des lapins chrétiens«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-03-05 - Charline , «Je m'en fous complètement des départementales, je prends l'autoroute«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-03-10 - «Balladur, nouvelle idole de l'UMP«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-04-27 - «Je vous confirme que Ségolène est douée pour prendre la tête«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-05-06 - «10 ans à suivre la politique sans aucune main au cul !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-05-14 - «Varoufakiss me baby...«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-05-27 - «Moi, Geneviève de Gaulle-Anthonioz, me v’là au Panthéon !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-06-19 - Jésus n'a pas dit , «Ceci est Monsanto«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-08-25 - «La Légion d'honneur, vous pouvez vous la carrer dans le train«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-08-27 - Pour Rebsamen, les chiffres du chomage tous les mois, c'était comme si les Anglais débarquaient«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-09-04 - «Cellule web de l'Élysée , parler aux jeunes, c'est bien , mais si c'est pour leur raconter la même chose qu'aux vieux, je ne vo.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-09-10 - J'ai regardé «Qui décrochera le job ¿« hier soir sur M6.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-09-18 -  «Prépas , en France, les hommes sont libres et égaux en droit...jusqu'au bac !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-09-21 - «Journées du Patrimoine , quand vous allez montrer votre selfie avec Macron, votre conseiller Pôle Emploi va moins la ramener«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-09-29 - Anne Hommel conseille Francis Lalanne , «Dites que c'était votre «part d'ombre« !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-10-16 -  «Le Pape , après un disque, et la couv' de Match, bientôt une fille cachée ¿«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-11-03 - Sarkozy vs «Air cocaïne«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-11-13 - Les gardes du corps, plutôt «Mme est servie« que «Starsky et Hutch«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-12-04 - Milice biterroise de Robert Ménard , «Village people« version 3eme âge.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2015-12-15 - «Valerie Pécresse pour le cumul... des soutiens gênants«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-01-15 - «Jean-François Copé , je suis extrèmement choqué«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-01-19 - «Mon plan d'urgence pour l'emploi« .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-02-02 - Il est loin le temps où un président lançait un «Castro, pauv' con !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-03-14 - En politique dans le texte , «Elle est où ta nuance ¿ Dans ton cumul«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-03-22 - «Jeanne..., au secours !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-03-23 - On est passé de «je suis en terrasse« à «je suis au check-in«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-04-07 - Édouard et Marie Christine, patrons, lancent «Le jour Couché«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-05-30 - Après «Hé oh la gauche«, «oz ta droite«, j'attends le «paye ton verre« des écolos !.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-06-14 - De Gaulle , «Que ces clampins me lâchent la nouille«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-06-20 - Ne nous «brexitons« pas.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-08-29 - Christian Estrosi ralliement d'un «motodidacte«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-08-31 - Le programme d'Emmanuel Macron en 3 points , 1) J'ai 2) un 3) projet.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-09-27 - «2 € pour virer Sarkozy, c'est donné !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2016-11-10 - Donald Trump président , «On te l'avait bien dit, tu n'as rien voulu voir venir«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-01-30 - «Je suis Pénélope«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-02-02 - La campagne électorale vue par «Ruth Elkabach« de Bfmmstv.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-02-22 - Emmanuel Macron à Londres , «This is my projeeect« ! .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-03-14 - Présidentielle , le parrainage électoral, un «filtre à hurluberlus« ¿ .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-03-17 - «Macron en visite à Merkel , es ist mein projeeeeekt !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-03-22 - [HUMOUR] Les filles de Bruno Le Roux , «On a trop du bol que papa soit de gauche« .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-04-06 - Clem et Jean-Mat , «Ta campagne, François, c'est Breaking bad !«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-04-20 - Inviter Fillon pour lui dire «Rends l'argent François«, ça ne se fait pas ! .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-04-27 - Défilé du 1er mai , «Tous ensemble, tous ensemble, ou presque, presque !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-06-01 - Nathalie Kosciusko-Morizet «J’ai tiré le gros lot avec ma circo !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-06-22 - «On peut être en marche et en rater une«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-06-28 - «La France, un pays nommé désir«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-10-11 - «L’Auberge catalane«, un remake du film de Cédric Klapisch.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-11-02 - «Chez Les Républicains, des expulsions avant la trêve hivernale«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-12-06 - «Johnny , il n'était pas dans la playlist...«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2017-12-14 - Visitez le «Jean-Marc Ayrault airport« et sa bulle géante, Zadiland .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-02-01 - «Peut-on rire de tout ¿«… Ben posez la question à Jawad, les gars !.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-02-06 - «Avec nous, c’est la tolérance des euros«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-02-13 - Il n'est pas né celui qui va «grand-remplacer« Nadine Morano.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-02-20 - Gérald Darmanin ,«Les yeux dans le slip«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-04-12 - Macron , «Bring me this Jean-Pernaut now !« Trump va être sous le charme.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-04-16 - Quand on mélange Bourdin et Plenel ça fait du «Bourdel«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-05-02 - «Saccager un MacDo alors qu'on n’a plus rien osé casser depuis le vase de Soissons !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-06-07 - «On a lancé la campagne de Grivouille (Benjamin Griveaux) à Paris« !.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-06-12 - Football , «Le 12 juillet 1998, le plus beau jour de ma vie !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-09-10 - Depardieu en Corée du Nord , «le régime Nord-Coréen, c’est le seul qu’il n’a pas encore essayé«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-09-17 - Jean-Michel Blanquer a raison «l'éducation, ça créé de la dette!«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-10-15 - Les nouveaux couples , «S’aimer, c’est regarder Netflix dans la même direction« .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-10-25 - Matthieu Pigasse, le banquier rockeur qui pourrait vendre «Le Monde« à un Tchèque.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-11-21 - «Il faut laisser la justice du Japon faire son travail«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2018-12-10 - Le portait d'Emmanuelle Wargon à la sauce «Paris-Match«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2019-02-21 - Hommage à un grand artisan, Gérard Manfroid , «le kaiser du radiateur«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2019-02-25 - «Imminence«, au salon de l'agriculture.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2019-03-20 - Greenwashing , Marine Le Pen et le concept d'«écologie identitaire«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2019-09-25 - «Bonjour les voleurs d'enfance, les briseurs d'avenir« , la présidente du fanclub de Greta Thunberg en France.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2020-04-03 - Continuité pédagogique , «J'étais prof, je suis devenu geek !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2020-04-21 - Trump , «Haut les mains, espèce de virus chinois !«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2020-05-05 - Culture et monde d'après ,«La flûte enchantée« à l'accordéon.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2020-05-13 - L'école est passée de «L'Instit« à «Prison break«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2020-05-14 - L'Académie française s'est réveillée , on dit «LA« Covid ! .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2020-06-22 - Une «quarantaine« de films pour la réouverture des salles.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2020-06-23 - «Génération COVID« ¿ Merci les boomers !.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2020-08-24 - Défaite du PSG , «Alors, vous avez le seum ¿« .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2020-09-28 - «Vols vers nulle part« , métaphore de l’époque.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2020-10-01 - «La bonne de l'imam« , Charline et Frédéric chantent la liberté d'expression.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2020-11-11 - Genevoix au Panthéon , «Maurice, on va faire une mise à jour«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2020-12-01 - «Etoile des neiges« .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2021-05-12 - «Moi, barrage contre l’extrême-droite«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2021-11-16 - «Je roule pour Poutou« .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2022-01-17 - «Meeting olfactif avec Eau de Méluche, Paris« .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2022-05-30 - « Pagaille 1 – Stade de France 0 .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2022-09-23 - «Je me mets en retrait«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2022-09-29 - Gazoduc , «fouite« dans la Baltique.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2022-11-22 - Eric Ciotti et «préliminaire«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2022-11-30 - McKinsey et les «abus«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2023-01-27 - Ne dites plus «les Français«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2023-04-19 - Le «congé« menstruel à Carrefour.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2023-12-03 - «Gros lardon«, le N+1 de l'ultra-droite.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2024-03-24 - Opération «Place nette«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2024-04-07 - Les «Poêles à frire Papers«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2024-06-16 - «J'espère que le rire va couvrir le bruit des bottes !«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2024-09-26 - Procès RN , «l'arbitre du gouvernement« devant la justice..m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2024-10-16 - Les espèces invasives grimpent dans «Les Petits Bateaux«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2024-11-07 - La statue de la Liberté est une «femme à chats« !.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2024-12-02 - Pour un «Institut du Scepticisme«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2024-12-09 - Elon Musk à Notre-Dame , «Y'a du Wi-Fi dans la nef ¿«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-01-08 - Le Pen , le papier journal de «Charlie« sera son linceul.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-01-14 - Ne dites plus «députés« mais «influenceurs loi«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-01-20 - «Sus à la techno-oligarchie, vive le techno-peuple !«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-01-21 - «Elon Musk , salut nazi ou érection du bras droit ¿«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-01-27 - «Vigilance des entreprises« , l'urgence climatique attendra .m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-01-29 - La Joconde , «Macron est chef d'État ou chef de chantier ¿«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-02-06 - «Pétain express«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-02-12 - La corruption a sa «french touch«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-03-17 - La vie en «Place publique«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-03-20 - «Compte-tenu du contexte international...«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-03-24 - «La Belle et Babeth«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-03-25 - Les cahiers de doléances laissés en «Vu«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-06-17 - Salon du Bourget , «Vive la paix, achetez nos armes !«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Charline Vanhoenacker\2025-06-19 - «Les honnêtes gens« (et fin de l'enquête sur Léa Salamé...).m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2016-05-06 - «T'as plein de sous, plein de blé«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2016-11-18 - «De toutes les primaires, c'est la droite que j'préfère«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2017-04-07 - «Laisse moi kiffer la thune avec mon mec«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2018-10-29 - «Johnny Hallyday va pas mieux«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2018-11-23 - «Libérez Carlos Ghosn !«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2019-01-03 - «Magic Jupiter« , la chanson de Magic system au louvre actualisée.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2019-07-06 - «Pousse, pousse sur les pédales«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2020-04-03 - Covid et Jonathan chantent «Est-ce que tu viens pour les urgences ¿«..mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2020-06-05 -  «Aime«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2020-10-23 - «Marignane-Vesoul«, le casse-tête des vacances à l'heure du coronavirus (en duo avec Constance).mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2020-12-18 - «Petit Booba Noël«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2020-12-28 - «Pas d’amish comme toi«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2020-12-30 - «La pollution c’est très très mal«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2021-04-20 - Leur «travail« c'est de chanter .mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2021-06-09 - «1 vieux, 1 problème«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2022-09-02 - «T'as beau dire qu'il fait beau«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2023-01-27 - «J'ai perdu ma couille dans une manif«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2023-05-19 - «Face à mon maire, je reste tranquille«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2023-09-10 - «Plante, vas-y plante«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Frédéric Fromet\2024-01-07 - Chanson de «soutien« à Gérard Depardieu.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\charline-explose-les-faits\2025-06-17 - Salon du Bourget , «Vive la paix, achetez nos armes !«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\charline-explose-les-faits\2025-06-19 - «Les honnêtes gens« (et fin de l'enquête sur Léa Salamé...).m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\charline-explose-les-faits\2025-09-03 - «C'est Nicolas qui paye« cette chronique !.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\charline-explose-les-faits\2025-09-11 - «Bloquons tout« , l'Assemblée a rejoint le mouvement en bloquant toutes les réformes .m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\la-chronique-de-benjamin-tranie\2025-05-20 - «Tranié raconte« une dernière fois , la mort des personnages de Benjamin Tranié.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\la-chronique-de-marine-leonardi\2025-05-05 - Marine Leonardi découvre le concept de «malbaise« ... pas du tout.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\la-chronique-de-marine-leonardi\2025-09-08 - Marine Leonardi pense que la «dysmorphie financière«, c'est bidon !.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\la-chronique-de-marine-leonardi\2025-09-29 - Marine Leonardi pensait que «cyberpunk«, c'était de la musique.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\la-chronique-de-rosa-bursztein\2025-05-13 - Amélia Doutretombe, poétesse gothique, déclame «Beauté des seins qui pendent«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\la-chronique-de-yann-marguet\2025-05-01 - Vivement qu'on dise «Le cinéma, c'est plus ce que c'était«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\la-chronique-de-yann-marguet\2025-09-04 - USAID , «nous sommes immondes«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\le-billet-de-daniel-morin\2025-05-27 - «Mandale«, palme d'or 2026 , un film bouleversant.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\le-billet-de-daniel-morin\2025-09-24 - Journée spéciale «Santé mentale« dans ta radio.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\le-billet-de-francois-morel\2025-05-23 - «L’Art de Bretécher«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\le-billet-de-matthieu-noel\2025-05-19 - Après Louane, au tour de Wauquiez d'appeler «mamaaan« !.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\le-billet-de-matthieu-noel\2025-05-27 - «Pas de France apaisée sans une République ferme« , on dirait un tatouage de Louis Sarkozy.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\le-billet-de-matthieu-noel\2025-06-03 - Même les «Jeunes avec Macron« veulent changer de nom !.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\le-billet-de-matthieu-noel\2025-06-24 - Le surnom de Léa Salamé ¿ «Sugar mommy« !.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\L'humour d'Inter\studio-payet\2025-08-31 -  Jérémie Renier, «Si regarder en arrière t'inspire du chagrin, si regarder en avant t'inspire de l'inquiétude, alors...«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Lisa Delmoitiez\2024-01-17 - «Titre«.mp3",
r"C:\Users\Pierr\Downloads\Podcasts\Lisa Delmoitiez\2024-09-17 - «La mort, c’est comme les étrangers«.m4a",
r"C:\Users\Pierr\Downloads\Podcasts\Lisa Delmoitiez\2025-03-18 - Je suis «délusionnelle«.m4a"
]

nf = 0
for file in files:
    nf += 1
    if not file_exists(file):
        print("*** Not found:", file)
    else:
        new_name = file.replace("«", "‹", 1).replace("«", "»").replace("‹", "«")
        print(new_name)
        os.rename(file, new_name)

print(nf, "files processed")