from typing import Iterable, List, Tuple

def get_files(source: str) -> List[str]: ...
def get_folders(source: str) -> List[str]: ...
def get_all_files(path: str) -> Iterable[str]: ...
def get_all_folders(path: str) -> Iterable[str]: ...
def file_part(fullpath: str) -> str: ...
def folder_part(fullpath: str) -> str: ...
def basename(filewithext: str) -> str: ...
def basename_part(filewithext: str) -> str: ...
def extension(filewithext: str) -> str: ...
def extension_part(filewithext: str) -> str: ...
def file_exists(fullpath: str) -> bool: ...
def folder_exists(fullpath: str) -> bool: ...
def file_size(fullpath: str) -> int: ...
def file_readalltext_encoding(filepath: str) -> Tuple[str, str]: ...
def file_readalltext(filepath: str) -> str: ...
